apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx
  namespace: lscsde-config
spec:
  suspend: ${nginx_ingress_suspended}
  force: false
  interval: 1m0s
  path: ./
  prune: true
  retryInterval: 1m0s
  serviceAccountName: flux-applier
  sourceRef:
    kind: GitRepository
    name: nginx
    namespace: lscsde-config
  timeout: 1m0s
  wait: false
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-config
    - kind: ConfigMap
      name: deployment-config