apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aks-dns-operator
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: lscsde-config-flux
    meta.helm.sh/release-namespace: lscsde-config
    lsc-sde.nhs.uk/definitionVersion: "1.0.1"
spec:
  targetNamespace: lscsde
  releaseName: aks-dns-operator
  chart:
    spec:
      chart: aks-dns-operator
      version: ${aks_dns_chart_version}
      sourceRef:
        kind: HelmRepository
        name: lsc-sde
        namespace: lscsde
  interval: 5m0s
  install:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  upgrade:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  valuesFrom:
  - kind: ConfigMap
    name: aks-dns-operator-config