apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: lscsde-workspace-mgr
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: lscsde-config-flux
    meta.helm.sh/release-namespace: lscsde-config
  name: lscsde-workspace-mgr