apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: analytics-workspace-management
  namespace: lscsde-config
spec:
  interval: 1m0s
  ref:
    branch: ${analytics_workspace_management_branch}
  timeout: 60s
  url: https://github.com/lsc-sde/iac-flux-analytics-workspace-management