apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-applier
  namespace: lscsde-workspace-mgr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-applier-binding:lscsde-workspace-mgr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: flux-applier
  namespace: lscsde-workspace-mgr
