apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyvault-sync
  namespace: secrets-distributor
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: lscsde-config-flux
    meta.helm.sh/release-namespace: lscsde-config
    xlscsde.nhs.uk/secretUsage: "Key Vault Sync"
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ${azure_client_id}
    keyvaultName: ${azure_keyvault_name}
    tenantId: "${azure_tenant_id}"
    objects: |
        array:
        - |
          objectName: PrimaryStorageAccountName
          objectType: secret
        - |
          objectName: PrimaryStorageAccountKey
          objectType: secret
        - |
          objectName: JupyterAppRegistrationClientSecret
          objectType: secret
        - |
          objectName: WildcardCertificate
          objectType: secret
        - |
          objectName: WildcardCertificateKey
          objectType: secret
        - |
          objectName: PatToken
          objectType: secret
        - |
          objectName: SqlHostName
          objectType: secret
        - |
          objectName: SqlAdministratorLogin
          objectType: secret
        - |
          objectName: SqlAdministratorPassword
          objectType: secret
        - |
          objectName: JupyterCookieSecret
          objectType: secret
        - |
          objectName: OhdsiDbPassword
          objectType: secret
        - |
          objectName: HadesPassword
          objectType: secret
        - |
          objectName: OhdsiAppRegistrationClientSecret
          objectType: secret