apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-applier
  namespace: ohdsi
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: lscsde-config-flux
    meta.helm.sh/release-namespace: lscsde-config
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-applier-binding:ohdsi
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: lscsde-config-flux
    meta.helm.sh/release-namespace: lscsde-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: flux-applier
  namespace: ohdsi
